require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*.rb'
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

Rails:
  Enabled: true
  
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Style/CommentedKeyword:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false


Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
  Exclude:
    - 'spec/**/*.rb'

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/SymbolArray:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Layout/AlignParameters:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'
