require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*.rb'
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0

Rails:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Naming/MethodParameterName:
  Enabled: false
  Exclude:
    - 'app/models/image.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Style/CommentedKeyword:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - 'spec/**/*.rb'
    - 'app/indices/*.rb'

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  Exclude:
    - 'config/routes.rb'

Style/StringLiterals:
  Exclude:
    - 'spec/**/*.rb'

Style/SymbolArray:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true
  Exclude:
    - 'lib/scripts/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Layout/ParameterAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
